export enum ENUM_EMPLOYEE_STATUS_CODE_ERROR {
    EMPLOYEE_NOT_FOUND_ERROR = 5400,
    EMPLOYEE_USERNAME_EXISTS_ERROR = 5401,
    EMPLOYEE_EMAIL_EXIST_ERROR = 5402,
    EMPLOYEE_MOBILE_NUMBER_EXIST_ERROR = 5403,
    EMPLOYEE_IS_ACTIVE_ERROR = 5404,
    EMPLOYEE_INACTIVE_ERROR = 5405,
    EMPLOYEE_PASSWORD_NOT_MATCH_ERROR = 5406,
    EMPLOYEE_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5407,
    EMPLOYEE_PASSWORD_EXPIRED_ERROR = 5408,
    EMPLOYEE_PASSWORD_ATTEMPT_MAX_ERROR = 5409,
    EMPLOYEE_BLOCKED_ERROR = 5410,
  }
  